FORMAT: 1A
HOST: https://api.skypicker.com

# Skypicker.com API
Skypicker.com flights search API.

The default api endpoint is api.skypicker.com . You have to use https, always.
Currently, SLLv3 is disabled. Use TLS 1, 1.1 or 1.2 in your client config, if you get a handshake error response.

To implement the basic search, you need only the /places and /flights API calls.

To implement also the booking API, you need to use the booking_token hash containing all the needed flights data and pass it as parameters to check flights and also to save booking calls.

The places call contains the list of Skypicker API IDs, which are accepted by the /flights call in the flyFrom and to parameters. Basically, the IDs are the IATA airport and ISO country codes, 
but Skypicker uses also its own IDs as the engine can do very specific searches (currently anywhere and there could be other geo areas specified - "To the sea", "To party places" etc)

# Partner implementation notes

Use the parameter partner=picky for testing your implementation. Before going live, your account manager will assign your custom partner ID to you.

There is no development API, as most of the queries are simple GET requests that are not changing the state of any resource (except save_booking).
Feel free to use api.skypicker.com for the implementation and also testing.

Currently, all of our flights are economy class. We consider for now each passenger as an adult.

# How it works
For every search the rules are the same. Except deeplink! How **deeplink** works - scroll down.

1. Always **start with** https://api.skypicker.com/

2. Choose **one specific call** from list below (places, flights, flights_multi, check_flights, save_booking, paymill_payment, zooz_payment, watchdog), 
e.g. https://api.skypicker.com/places

3. For **specific searches** and filters use " **?** " after chosen call, e.g. /places?
Then **choose parameters** from specific call list, where every available parameter is described. 
Choose one of them and use it in exact form with " **=** ". Then **set a value** of the parameter,  e.g. https://api.skypicker.com/places?term=br
So term is used for suggestions of geo names and "br" returns city, airport codes or country names beginning with br.

You may want to **combine** more parameters, then always put " **&** " to separate them, e.g. https://api.skypicker.com/places?term=br&locale=cs
Now we have all geo names beginning with br in Czech language.

Some of the parameters are **mandatory** for use in specific calls. Check it in **Details** column of every parameter, 
e.g. in **flights search** parameters flyFrom, to, dateFrom and dateTo are required https://api.skypicker.com/flights?flyFrom=PRG&to=LGW&dateFrom=18/06/2017&dateTo=25/06/2017&partner=picky.
We get all flights from Prague to London, from May 18, 2017 until May 25, 2017

Correct date format is **dd/mm/YYYY**, e.g. 29/05/2015. 


#### Places [/places]
The basic places call is this

https://api.skypicker.com/places

#### Search
The basic flights call could look like this

https://api.skypicker.com/flights?flyFrom=PRG&to=LGW&dateFrom=18/06/2017&dateTo=25/06/2017&partner=picky

If there is the partner parameter specified, the response will contain the link directly to Skypicker booking, where user can book the specified flight.

For more specific searches and filters continue to this apiary specification, where every available parameter is described.

In case you can't find what you're looking for here in docs, please, contact us directly at **api@kiwi.com**.

## Group places

Returns the list of Skypicker api ids. This ids has to be used in the SP search (flights API call)
From v2 (May 2014) flights also accepts parameters for city areas (LON,PAR...), even if they dont appear in the places call

## places [/places{?id,term,locale,zoomLevelThreshold,bounds,v}]

### GET [GET]


+ Parameters
    + id : SK (optional, string) - if given, the call returns the details only for the one specific id
    + term : br (optional, string) - used for suggestions of geo names,"br" returns city, airport codes or country names beginning with br
    + locale : cs (optional, string) - the locale of geo names in response, default is en
    + zoomLevelThreshold : `3` (optional, integer) - zoom level on which this place should be shown. DEPRECATED
    + bounds : lat_lo,lng_lo,lat_hi,lng_hi (optional, string) - filter only places in these bounds. "lo" corresponds to the southwest corner of the bounding box, "hi" corresponds to the northeast corner of that box
    + v : 1 (optional, integer)  - the api version, from v = 2 it returns the new api ids for the whole world. Every new partner should use v = 3

+ Request
    
        { "term":"BRQ" }

+ Response 200

        {
            "zoomLevelThreshold": 7,
            "numberOfAirports": 1,
            "sp_score": null,
            "value": "Brno",
            "rank": 8,
            "parentId": 1,
            "lat": 49.1952,
            "lng": 16.608,
            "type": 0,
            "id": "BRQ"
        }

## Group flights

A single flights search.

The google flights like filters (price_from,price_to and the next ones) are not well documented and even not tested for properly functioning, yet. 

## flights [/flights{?flyFrom,to,dateFrom,dateTo,longitudeFrom,latitudeFrom,radiusFrom,longitudeTo,latitudeTo,radiusTo,daysInDestinationFrom,daysInDestinationTo,returnFrom,returnTo,typeFlight,passengers,adults,children,infants,flyDays,oneforcity,onlyWorkingDays,onlyWeekends,one_per_date,directFlights,locale,partner,partner_market,v,limit,offset,xml,curr,price_from,price_to,dtimefrom,dtimeto,atimefrom,atimeto,returndtimefrom,returndtimeto,returnatimefrom,returnatimeto,stopoverfrom,stopoverto,booking_token,sort,asc}]

### GET [GET]

+ Parameters

    + flyFrom (required, string,`CZ`) ... Skypicker api id of the departure destination. 
        Accepts multiple values separated by comma, these values might be airport codes, 
        city IDs, two letter country codes, metropolitan codes and radiuses. 
        Radius needs to be in form lat-lon-xkm. E.g. `-23.24--47.86-500km` for places 
        around Sao Paulo, LON - checks every airport in London, LHR - checks flights 
        from London Heathrow, UK - flights from United Kingdom 
    + to (optional, string, `porto`) ... Skypicker api id of the arrival destination. 
        Accepts the same values in the same format as `flyFrom` parameter. 
    If you don't include any value you'll get results for all the airports in the world.
    + dateFrom (required, string,`08/08/2017`) ... search flights from this date (dd/mm/YYYY). **Use parameters dateFrom and dateTo as a daterange for the flight departure.**
        Parameter dateFrom 01/05/2016 and dateTo 30/05/2016 means, that the departure can be anytime between those dates.
        For the dates of the return flights, use the returnTo&returnFrom or daysInDestinationFrom & daysInDestinationTo parameters
    + dateTo (required, string,`08/09/2017`) ... search flights until this date (dd/mm/YYYY)

    + longitudeFrom : 14.0000 (optional, float) - DEPRECATED - please use radiuses 
        specified in **flyFrom** parameter (longitude of the pinpoint for geo based search, 
        for the departure destination)
    + latitudeFrom : 50.2000 (optional, float) - DEPRECATED (lat of the pinpoint for 
        geo based search, fot the departure destination)
    + radiusFrom : 200 (optional, integer) - DEPRECATED (search radius in km, max 250.
        **radiusFrom** works only with **longitudeFrom** and **latitudeFrom**. 
        In this case, the **flyFrom** parameter is ignored)
        
    + longitudeTo : 14.0000 (optional, float) - DEPRECATED - please use radiuses 
        specified in **to** parameter (longitude of the pinpoint for geo based, for the 
        arrival destination)
    + latitudeTo : 50.2000 (optional, float) - DEPRECATED (lat of the pinpoint for 
        geo based search, for the arrival destination)
    + radiusTo : 200 (optional, integer) - DEPRECATED (search radius in km, max 250.
        **radiusTo** works only with **longitudeTo** and **latitudeTo**. In this case, 
        the **to** parameter is ignored)
    
    + daysInDestinationFrom : 2 (optional, integer) - the minimal length of stay in the destination given in the **to** parameter. Counts nights, not days
    + daysInDestinationTo : 14 (optional, integer) - the max length of stay in the destination given in the **to** parameter
        (use only one from the daysInDestination and returnFrom/returnTo parameters. If both of them are given, the API uses the daysInDest parameters
        and the return dates are ignored). When you omit one of these two params, the default value for daysInDestinationFrom is 1 and for daysInDestinationTo is 14.
    
    + returnFrom : 08/08/2017 (optional, string) - min return of the whole trip (dd/mm/YYYY)
    + returnTo : 08/09/2017 (optional, string) - max return date of the whole trip (dd/mm/YYYY)
    
    + typeFlight (optional, string, `oneway`) ... switch for oneway/round flights search - will be deprecated in the near future
        (until then, you have to use the round parameter if one from the daysInDestination of returndate parameters is given.)
        
        + Values
            + `round`
            + `oneway`
            
    
    + oneforcity : 0 (optional, boolean) - returns the cheapest flights to every city covered by the **to** parameter. E.g. if you set it to 1 and your search is from PRG to LON/BUD/NYC, you'll get 3 results: the cheapest PRG-LON, the cheapest PRG-BUD, and the cheapest PRG-NYC.
    + one_per_date : 0 (optional, boolean) - returns the cheapest flights for one date. Can be 0 or not included, or one of these two params can be set to 1
    
    + passengers : 1 (optional, integer) - number of passengers. Default for defining the num of passengers.
    
    + adults : 1 (optional, integer) - To specify number of adults, children, and infants, you can use adults&children&infants parameters. You have to specify all of those 3 parameters, otherwise the parameter passengers will be used. However, currently childs&infants are considered as adults in our search engine and are not reqiured, default adults value is 1
    + children : 0 (optional, integer) - number of children
    + infants : 0 (optional, integer) - number of infants
    
    + flyDays : [0,1,2,3,4,5,6] (optional, list) - the list of week days for the flight, 0 is Sunday (**flyDaysType** is used to tell if the days should be departure or arrival of the flight,
        url encoded format for all days: flyDays%5B%5D=0&flyDays%5B%5D=1&flyDays%5B%5D=2&flyDays%5B%5D=3&flyDays%5B%5D=4&flyDays%5B%5D=5&flyDays%5B%5D=6)
    
    + flyDaysType (optional, string, `departure`) ... type of set flyDays, 
        
        + Values
            + `departure`
            + `arrival`

    + returnFlyDays : [0,1,2,3,4,5,6] (optional, list) - the list of week days for the departure, 0 is Sunday (**returnFlyDaysType** is used to tell if the days should be departure or arrival of the flight,
        url encoded format for all days: returnFlyDays%5B%5D=0&returnFlyDays%5B%5D=1&returnFlyDays%5B%5D=2&returnFlyDays%5B%5D=3&returnFlyDays%5B%5D=4&returnFlyDays%5B%5D=5&returnFlyDays%5B%5D=6)
    
    + returnFlyDaysType (optional, string, `departure`) ... type of set returnFlyDays
        
        + Values
            + `departure`
            + `arrival`
    
    + onlyWorkingDays : 0 (optional, boolean) - search flights with departure only on working days
    + onlyWeekends : 0 (optional, boolean) - search flights with departure only on weekends 
    + directFlights : 0 (optional, boolean) - search only for direct flights, can be set to 0 or 1, 0 is default

    + partner : picky (required, string) - partner ID. If present, in the result will be also a link to a specific trip directly to skypicker.com, with the affiliate id included (use picky partner ID for testing)
    + partner_market : us (required, string) - Market from which the request is coming from.
    + v : 2 (optional, integer) - api version, defaults to 1, in case of 2 the response format contains additional information (country codes and names, for now used only on skypicker.com frontend)
    
    + xml : 0 (optional, integer) - returns an xml response instead of json
    + curr (optional, string, `EUR`) ... use this parameter to change the currency in the response
        
        + Values
            + `AED`
            + `AFN`
            + `ALL`
            + `AMD`
            + `ANG`
            + `AOA`
            + `ARS`
            + `AUD`
            + `AWG`
            + `AZN`
            + `BAM`
            + `BBD`
            + `BDT`
            + `BGN`
            + `BHD`
            + `BIF`
            + `BMD`
            + `BND`
            + `BOB`
            + `BRL`
            + `BSD`
            + `BTC`
            + `BTN`
            + `BWP`
            + `BYR`
            + `BZD`
            + `CAD`
            + `CDF`
            + `CHF`
            + `CLF`
            + `CLP`
            + `CNY`
            + `COP`
            + `CRC`
            + `CUC`
            + `CUP`
            + `CVE`
            + `CZK`
            + `DJF`
            + `DKK`
            + `DOP`
            + `DZD`
            + `EEK`
            + `EGP`
            + `ERN`
            + `ETB`
            + `EUR`
            + `FJD`
            + `FKP`
            + `GBP`
            + `GEL`
            + `GGP`
            + `GHS`
            + `GIP`
            + `GMD`
            + `GNF`
            + `GTQ`
            + `GYD`
            + `HKD`
            + `HNL`
            + `HRK`
            + `HTG`
            + `HUF`
            + `IDR`
            + `ILS`
            + `IMP`
            + `INR`
            + `IQD`
            + `IRR`
            + `ISK`
            + `JEP`
            + `JMD``
            + `JOD`
            + `JPY`
            + `KES`
            + `KGS`
            + `KHR`
            + `KMF`
            + `KPW`
            + `KRW`
            + `KWD`
            + `KYD`
            + `KZT`
            + `LAK`
            + `LBP`
            + `LKR`
            + `LRD`
            + `LSL`
            + `LTL`
            + `LVL`
            + `LYD`
            + `MAD`
            + `MDL`
            + `MGA`
            + `MKD`
            + `MMK`
            + `MNT`
            + `MOP`
            + `MRO`
            + `MTL`
            + `MUR`
            + `MVR`
            + `MWK`
            + `MXN`
            + `MYR`
            + `MZN`
            + `NAD`
            + `NGN`
            + `NIO`
            + `NOK`
            + `NPR`
            + `NZD`
            + `OMR`
            + `PAB`
            + `PEN`
            + `PGK`
            + `PHP`
            + `PKR`
            + `PLN`
            + `PYG`
            + `QAR`
            + `QUN`
            + `RON`
            + `RSD`
            + `RUB`
            + `RWF`
            + `SAR`
            + `SBD`
            + `SCR`
            + `SDG`
            + `SEK`
            + `SGD`
            + `SHP`
            + `SLL`
            + `SOS`
            + `SRD`
            + `STD`
            + `SVC`
            + `SYP``
            + `SZL`
            + `THB`
            + `TJS`
            + `TMT`
            + `TND`
            + `TOP`
            + `TRY`
            + `TTD`
            + `TWD`
            + `TZS`
            + `UAH`
            + `UGX`
            + `USD`
            + `UYU`
            + `UZS`
            + `VEF`
            + `VND`
            + `VUV`
            + `WST`
            + `XAF`
            + `XAG`
            + `XAU`
            + `XCD`
            + `XDR`
            + `XOF`
            + `XPD`
            + `XPF`
            + `XPT`
            + `YER`
            + `ZAR`
            + `ZMK`
            + `ZMW`
            + `ZWL`
            
            
    
    + locale (optional, string, `en`) ... the language of city names in the response
        (more translations to be added)
        + Values
            + `en`
            + `cs`
            + `pl`
            + `pt`
            + `it`
            + `de`
            + `fr`
            + `ru`
            + `hu`
            + `sk`
            + `el`
            + `fi`
            + `nl`
            + `se`
            + `ar`
            + `br`
            + `cs`
            + `da`
            + `de`
            + `el`
            + `en`
            + `es`
            + `fa`
            + `fi`
            + `fr`
            + `he`
            + `hu`
            + `is`
            + `it`
            + `ja`
            + `ko`
            + `lt`
            + `my`
            + `nl`
            + `no`
            + `pl`
            + `pt`
            + `ro`
            + `ru`
            + `se`
            + `sk`
            + `sr`
            + `sv`
            + `th`
            + `tr`
            + `uk`
            + `ur`
            + `yi`
            + `zh`

    + price_from : 1 (optional, integer) - result filter, minimal price
    + price_to : 10000 (optional, integer) - result filter, maximal price

    + dtimefrom : 00:00 (optional, string) - result filter, min. departure time (11:00 means 11AM, 23:00 means 11PM, everyone of this time filter has the some format)
    + dtimeto : 00:00 (optional, string)  - result filter, max departure time
    + atimefrom : 00:00 (optional, string) - result filter, min arrival time
    + atimeto : 00:00 (optional, string)  - result filter, max arrival time
    + returndtimefrom : 00:00 (optional, string) - result filter, min dep. time of the returning flight
    + returndtimeto : 00:00 (optional, string) - result filter, max dep. time of the returning flight
    + returnatimefrom : 00:00 (optional, string) - result filter, min arrival time of the returning flight
    + returnatimeto : 00:00 (optional, string) - result filter, min arrival time of the returning flight
    + stopoverfrom : 00:00 (optional, string) - result filter, min length of stopover, 48:00 means 2 days here (48 hours)
    + stopoverto : 00:00 (optional, string) - result filter, max length of stopover, 48:00 means 2 days here (48 hours)

    + booking_token : hashed data (optional, string) - a hash containing the encrypted flight data. This hash should be passed to check flights and save booking API calls in the booking v2 API
    
    + offset : 0 (optional, integer) - enable pagination and set offset
    + limit : 30 (optional, integer) - limit number of results, max is 200
    + sort : price (optional, string) - sorts the results by quality, price, date or duration. Price is the default value
    + asc : 1 (optional, integer) - can be set to 1 or 0, default is 1 - from cheapest flights to the most expensive
    
    
    
+ Response 200 (application/json)

        {
          "search_params": {
            "to_type": "airport",
            "flyFrom_type": "airport"
          },
          "time": 1,
          "connections": [],
          "currency": "pln",
          "currency_rate": 0.2353,
          
        
          "data": [
            {
              "mapIdfrom": "edinburgh",
              "return_duration": "10h 55m",
              "flyTo": "WMI",
              "conversion": {
                "PLN": 1154,
                "EUR": 271
              },
              "deep_link": "https://www.skypicker.com/deep?type=abc-m14.5&from=EDI&to=WMI&departure=19-12-2015&return=23-12-2015&flightsId=240466858|236557749|245258276|234220297&affilid=skyscanner_pl&price=271.5362&passengers=1&lang=pl&currency=pln&booking_token=NwyrOTUtH6wv4BdWZTvOrbnFTa5SOifCjnpGoAl4cKO2kB2HhT7afLhR/TDxb+eFu4YtIczyK0WbM+XCt51oGwDK7vohxDpNs2GE3fTG8FoBhxY59V7abVbbkEWcRIOXaJcmIZB1tq37mciGQWi4Sc29PEWEgFYVwxJYBIOJMNLYkB8FOhhUNMDmnaVNHDOgySMJd4it4r5fhopJczkKnJIKoMFEelHE0x5203/3dHkfA7iBk4/c1OYTA61XBIAlsCuTH4D0j0IHASTFV4VXT36kZS9oxvJuya4nyDoff2017Up/UHkaXQbNBAoD5W0A",
              "mapIdto": "warsaw",
              "nightsInDest": 3,
              "id": "240466858|236557749|245258276|234220297",
              "fly_duration": "24h 10m",
              "countryTo": {
                "code": "PL",
                "name": "Rzeczpospolita Polska"
              },
              "baglimit": {
                "hand_width": 40,
                "hand_length": 55,
                "hold_weight": 15,
                "hand_height": 20,
                "hand_weight": 10
              },
              "aTimeUTC": 1450643100,
              "distance": 1624.4,
              "price": 1154,
              "type_flights": [
                "lcc"
              ],
              "bags_price": {
                "1": 100.0,
                "2": 200.0
              },
              "cityTo": "Warszawa",
              "flyFrom": "EDI",
              "dTimeUTC": 1450556100,
              "p2": 232,
              "countryFrom": {
                "code": "GB",
                "name": "Zjednoczone Królestwo Wielkiej Brytanii"
              },
              "p1": 232,
              "dTime": 1450556100,
              "booking_token": "NwyrOTUtH6wv4BdWZTvOrbnFTa5SOifCjnpGoAl4cKO2kB2HhT7afLhR/TDxb+eFu4YtIczyK0WbM+XCt51oGwDK7vohxDpNs2GE3fTG8FoBhxY59V7abVbbkEWcRIOXaJcmIZB1tq37mciGQWi4Sc29PEWEgFYVwxJYBIOJMNLYkB8FOhhUNMDmnaVNHDOgySMJd4it4r5fhopJczkKnJIKoMFEelHE0x5203/3dHkfA7iBk4/c1OYTA61XBIAlsCuTH4D0j0IHASTFV4VXT36kZS9oxvJuya4nyDoff2017Up/UHkaXQbNBAoD5W0A",
              "cityFrom": "Edynburg",
              "aTime": 1450646700,
              
              "route": [
                {
                  "bags_recheck_required": false,
                  "aTimeUTC": 1450560300,
                  "mapIdfrom": "edinburgh",
                  "mapIdto": "dublin",
                  "flight_no": 819,
                  "dTime": 1450556100,
                  "latTo": 53.3331,
                  "flyTo": "DUB",
                  "return": 0,
                  "source": null,
                  "id": "240466858",
                  "airline": "FR",
                  "lngTo": -6.24889,
                  "cityTo": "Dublin",
                  "cityFrom": "Edynburg",
                  "lngFrom": -3.1936633587,
                  "aTime": 1450560300,
                  "flyFrom": "EDI",
                  "price": 21.0,
                  "latFrom": 55.9485946759,
                  "dTimeUTC": 1450556100
                },
                {
                  "bags_recheck_required": true,
                  "aTimeUTC": 1450643100,
                  "mapIdfrom": "dublin",
                  "mapIdto": "warsaw",
                  "flight_no": 4543,
                  "dTime": 1450633200,
                  "latTo": 52.2298,
                  "flyTo": "WMI",
                  "return": 0,
                  "source": null,
                  "id": "236557749",
                  "airline": "FR",
                  "lngTo": 21.0118,
                  "cityTo": "Warszawa",
                  "cityFrom": "Dublin",
                  "lngFrom": -6.24889,
                  "aTime": 1450646700,
                  "flyFrom": "DUB",
                  "price": 133.0,
                  "latFrom": 53.3331,
                  "dTimeUTC": 1450633200
                },
                {
                  "bags_recheck_required": true,
                  "aTimeUTC": 1450914900,
                  "mapIdfrom": "warsaw",
                  "mapIdto": "dublin",
                  "flight_no": 4544,
                  "dTime": 1450907400,
                  "latTo": 53.3331,
                  "flyTo": "DUB",
                  "return": 1,
                  "source": null,
                  "id": "245258276",
                  "airline": "FR",
                  "lngTo": -6.24889,
                  "cityTo": "Dublin",
                  "cityFrom": "Warszawa",
                  "lngFrom": 21.0118,
                  "aTime": 1450914900,
                  "flyFrom": "WMI",
                  "price": 63.0,
                  "latFrom": 52.2298,
                  "dTimeUTC": 1450903800
                },
                {
                  "bags_recheck_required": true,
                  "aTimeUTC": 1450943100,
                  "mapIdfrom": "dublin",
                  "mapIdto": "edinburgh",
                  "flight_no": 812,
                  "dTime": 1450938600,
                  "latTo": 55.9485946759,
                  "flyTo": "EDI",
                  "return": 1,
                  "source": null,
                  "id": "234220297",
                  "airline": "FR",
                  "lngTo": -3.1936633587,
                  "cityTo": "Edynburg",
                  "cityFrom": "Dublin",
                  "lngFrom": -6.24889,
                  "aTime": 1450943100,
                  "flyFrom": "DUB",
                  "price": 15.0,
                  "latFrom": 53.3331,
                  "dTimeUTC": 1450938600
                }
              ]
            }
         ]
        }

## Group flights_multi


This call is able to do multi-city searches in parallel. The single search queries dont have to be connected in any way.

Accepts the same parameters as the /flights API call.

To do a request, send a POST json payload with a list of API parameters for each search query.

A sample python code for this call could look like the following (this is an example, all of the /flights parameters can be used)

In the response root, the results field contains a list of responses for the posted queries. Each single element contains the same response as it would be a /flights API call.

Please keep in mind, that valid json quotes are only ", not '

Each result has its own deeplink which can be used to forward the user to Skypicker booking e.g. 
https://www.skypicker.com/deep?type=default&from=PRG&to=LGW&departure=24-05-2017&flightsId=EJ635397264_189412776%7CEJ635397264_203224652&affilid=picky&price=78&passengers=1&lang=en&currency=GBP&booking_token=GamFTRHoBQ%2Fv6QB8IrykhpoVGKB0KA6sVANbFz24Dysa%2Btv8RDKePuXd0gMoWNZtroOXF%2BfO3fCLZ2ifi2bX%2F6pARs2%2BL4SCj%2FMPCz7A8VhRbcA3l2oWqbFdLAgK5KoX1GbT8rDRzbX74ht5Kt6dSHkGKFj%2F60E5Te1YshXVQhgZWzaFAuQ%2BZQ8X%2BMZ9YTwafUFV6K64YKFEF1%2BLPpUlcmqGNY9vzERgsQEfNLUUrCpDbkVRsgcXZMo8I3kt%2BG9B0a6IUViEKm328bxTLQOyAbsv0Eyf469eMuPyNNupwBEBDHWxfYgRz8lsayiRSXSbRMa4i1FpG0buiPdstLs8I3zRZsBvkzx4N525ePFeqMDhDCr6uBkf6xSkMmjiQAUBlsjVW2lvtQJGFr2ihNNuNlZTAL86RR22aGJ0abCzvcY%3D

The total_price is the sum of all the prices.

The main_booking_token in the response root should be used for booking the flights, instead the booking_token in each single search query result.

## flights_multi [/flights_multi{?partner,locale,curr}]

### POST [POST]

+ Parameters
    + partner : `picky` (required, string) - your partner ID
    + locale : `en` (optional, string) - localization, if you are using it for flights
    + curr : `GBP` (optional, string) - currency, if you are using it for flights
    

+ Request (application/json)
        
        {
            import requests
            import json
            
            r = {"requests": [
                    {"to": "PRG", "flyFrom": "AMS", "directFlights": 0, "dateFrom": "11/06/2016", "dateTo": "28/06/2016"},
                    {"to": "AMS", "flyFrom": "OSL", "directFlights": 0, "dateFrom": "01/07/2016", "dateTo": "11/07/2016"}
            ]}
            
            print requests.post('https://api.skypicker.com/flights_multi?partner=partnerID', data = json.dumps(r) ).json()
        }


## Group check_flights

Please see our booking documentation http://docs.skypickerbookingapi1.apiary.io/#reference/check-flights

## Group save_booking

Please refer to our documentation on save_booking http://docs.skypickerbookingapi1.apiary.io/#reference/save-booking

## Group confirm_payment

Please see our documentation on confirm_payment http://docs.skypickerbookingapi1.apiary.io/#reference/payment/confirmpayment

## Group check_itinerary

Request JSON data:

+ price - is price in eur.
+ segments - contains all flight segment what is needed to book with one itenerary:

    + airline - code of airline
    + dtime - departure time in local time of single flight
    + atime - arrival time in local time of single flight
    + src - departure airport
    + dst - destination airport
    + flight_no - flight number
    + itinerary_id - increment id of itinerary what will be used as pairing key what needs to be booked together as one pnr.
    + fare_code(optional) - fare code prefered on booking
+ passengers - details about passengers - see below
    
Date sent in response:

+ request - in request will be all requested details.
+ booking_details - informations needed to process booking
    + price - verified price of flights for how much we can process that flights booking
    + valid - if we are unable process this booking, than valid will be false. (It can happen when flights are not available anymore)
    + booking_token - booking token what will be used for call to booking api.
    + guarantee_applied - list of connections where guarantee will be applied


### POST /check_itinerary

+ Request (application/json)

        {
            "passengers": {
                "infants": 0,
                "adults": 1,
                "children": 0
            },
            "segments": [
                {"src":"PRG","itinerary_id":1,"flight_no":1198,"dtime":1467197400,"airline":"QS","atime":1467210600,"dst":"SVO"},
                {"src":"SVO","itinerary_id":2,"flight_no":1199,"dtime":1467732000,"airline":"QS","atime":1467738600,"dst":"PRG"}
            ],
            "price":198
        }

+ Response 200 (application/json)

        {
            "request": {
                "segments":[
                    {"airline":"DE","dtime":29839230923,"atime":"932809283023","src":"PRG","dst":"STN","flight_no":1392,"itinerary_id":1, "fare_code": "Y"},
                    {"airline":"SU","dtime":29839230923,"atime":"932809283023","src":"STN","dst":"VRO","flight_no":2983,"itinerary_id":2}
                ],
                "price": 299,
                "passengers": {
                    "infants": 0,
                    "adults": 1,
                    "children": 0
                }
            },
            "booking_details": {
                "price": 310,
                "valid": true,
                "booking_token": "2938394U98FDJKSBJFKH IUZ4B98NZ3IOVHSJFGJHKFGD O87B3Z498UHJFSHHGGBW87VZWPUIHDAOBZ3B4bZ89RUHADS",
                "guarantee_applied": [
                    1
                ]
            }
        }